[feat] 나의 단체 뷰 구현
TeamPINGLE/PINGLE-ANDROID pull request #201
Opened 2024-02-24 15:11 UTC by HAJIEUN02

## Related issue 🛠
- closed #194 

## Work Description ✏️
- [x] 현재 단체 정보 : LocalDataSource에 저장
- [x] 현재 내 단체 - 메뉴
    - [x] 메뉴 아이콘 클릭 시 visible/invisible 처리
    - [x] 메뉴-초대코드 복사하기 : ClipboardManager
    - [x] 메뉴-초대코드 복사하기 : 복사 완료 시 CustomSnackbar 띄우기
    - [x] 메뉴-공유하기 : chooser
- [x] Scroll 영역
     - [x] 멀티뷰타입 사용, viewType 2개(단체장 왕관 타입, 기본 타입) 
     - [x] 단체 클릭 시 해당 단체로 변경 프로세스 : CustomDialogFragment
- [x] 하단 '새로운 단체 추가하러 가기' 텍스트뷰 버튼 : 신규 단체 생성 프로세스로 이동

## Screenshot 📸
<img src="" width="360"/>

## Uncompleted Tasks 😅
- [ ] 단체 변경 로직
- [ ] 모달 새로 만들기(detail이 없는 모달이 나의 단체 뷰에 있어서 마진 값 수정된 버전의 모달이 필요합니다!)
- [ ] chip 머지되면 적용(현재 PingleBadge로 되어있음)

## To Reviewers 📢
단체 변경 프로세스 로직을 어떻게 해야할지 한참 고민하다가 일단 그거 제외한 다른 거부터 하자 해서 후딱 했습니다ㅜㅜ 고민을 하루 꼬박 했는데 잘 안 되더라구요.. 쩝
내일 일어나자마자 또 달려보구 이전 피알 포함 코리 반영해서 올릴게욥 ㅜ.ㅜ

2024-02-25 03:59 UTC, Dan2dani reviewed
복사하기나 공유하기 누르고 나서 띄워져있는 뭐라고 해야하지 네모 박스 안사라져도 되나영?

2024-02-25 03:59 UTC, Dan2dani commented on app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
> +    override var meetingCount: String
오옹,, 이 정보 서버에서 아무것도 안내려주는건가요..? 어느 api에서도,,?

2024-02-25 03:59 UTC, Dan2dani commented on app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
> +    override var meetingCount: String
서버에서 내려주는 값이 있고 그거 사용할 수 있다면 너무 많은 정보를 로컬에 저장해놓는건 핸드폰 기종에 따라 약간 무리일수도 ~~

2024-02-25 03:59 UTC, Dan2dani commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupAdapter.kt
> +            2
상수화 하는게 좋겠네여 ~~

2024-02-25 05:37 UTC, jihyunniiii commented
선생님 이거 지금 빌드가 안 되는 것 같은데 확인 한 번만 부탁드려용 ! 일단 빌드 되게 바꿔놓고 코리 달고 있을게용

2024-02-25 06:05 UTC, HAJIEUN02 commented
> 선생님 이거 지금 빌드가 안 되는 것 같은데 확인 한 번만 부탁드려용 ! 일단 빌드 되게 바꿔놓고 코리 달고 있을게용

어 마자요 그 모달 이미 만들어져 있는 거에 detail이 null이어야 작동해서 그렇게 수정해두고 커밋은 안 했거든욥
그래서 그 모달은 새로 만들 겁니당!!

2024-02-25 06:19 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupAdapter.kt
> +            2
넹 반영해서 상수화 했숨다!!

2024-02-25 06:27 UTC, jihyunniiii reviewed
수고하셨숩니당

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
> +    override var meetingCount: String
이거 단체 디테일 조회 API 있어서 그거 사용하면 될 듯 합니다 ~

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/domain/model/GroupListEntity.kt
List 형태가 아니니 네이밍을 다른 걸 사용하는 게 어떨까요,,? UserGroup, MyGroup 이런 느낌?

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +    }
이거 그냥 finish()만 하는 건 따로 구현 안 해도 되지 않나요?

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            )
개인적으로 String으로 빼주는 게 나을 것 같네용

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        clipboard.setPrimaryClip(clip)
복사기능 민우 오빠도 사용해야 하니까 Util로 옮겨도 좋을 듯요!!!

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        startActivity(Intent.createChooser(intent, null))
마찬가지로 Util로 !!!
chooserTitle도 기획 측에 어떤 걸로 할 지 정해달라고 하면 좋을 것 같네요 null로 하지 말구
그리고 추가로 여기 with를 사용한 이유는 멍가요?
다른 인텐트에는 apply를 사용했는데 여기만 with인 이유가 궁금해서요 ~

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        }
함수화 쩐다잉 ㄷ.ㄷ

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupAdapter.kt
> +            else -> throw RuntimeException()
마찬가지로 catch 로직이 있어야 할 것 같습니다

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/drawable/ic_my_group_list_owner.xml
이거 피그마에 있는 네이밍 따라가주세염
ic_my_group_selected_owner_58
나머지도 수정 부탁드려용

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/drawable/shape_border_white_radius_12.xml
네이밍 통일 시켜 주세요 shape_line_white_radius_12
그리고 solid 값 넣지 말구 테두리만 drawable 만들어주시고 foreground에 적용하는 방식으로 바꿔주세요 (마이핑글 팝업 버튼 참고하면 편할 듯요)

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/item_my_group.xml
> +                android:id="@+id/tag_my_group_list_default"
```suggestion
                android:id="@+id/chip_my_group_default_keyword"
```
pingleTag는 커스텀뷰 아니구 그냥 칩에 스타일 적용 아닌가염??
그리고 네이밍 뷰나 뷰그룹_어떤뷰인지_설명 이걸로 통일 부탁이요 ~

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/item_my_group.xml
item_my_group_default

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/item_my_group_owner.xml
여기도 위와 동일하게 네이밍 수정 부탁드려요

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +        <import type="android.view.View" />
이거 임포트한 이유가 뭔가요?

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            type="org.sopt.pingle.data.datasource.local.PingleLocalDataSource" />
localStorage를 여기 변수로 넣은 이유가 있나요? myGroupViewModel에서 해당 값을 다 불러와서 저장하지 않나요?

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            android:id="@+id/toolbar"
네이밍 컨벤션 따라주세요

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            android:id="@+id/layout_my_group_now"
now보다 직관적인 네이밍 없을까요? selected? 뭐 이런 거,,

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +                android:textColor="@color/white"
g_01

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +                android:layout_marginStart="45dp"
큰 마진 값을 주는 것 보다 start를 tv_my_group_now_meeting_count의 start에 주는 방법은 어떨까요?

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            android:paddingHorizontal="@dimen/spacing16"
패딩 안 주고 start랑 end를 가이드 라인에 줘도 될 것 같네요 ~

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            android:background="@color/g_10"
background로 shape 지정해주고 backgroundTint 적용해주셔야 합니둥

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            android:gravity="center"
wrapcontent로 해줬으면 이거 안 줘도 되지 않나요?

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            android:layout_marginBottom="20dp"
상하로도 중앙 정렬이라 상하 제약 다 줬으면 빼도 될 것 같습니당

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +            android:layout_marginEnd="7dp"
top margin 없서욤

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/res/layout/activity_my_group.xml
> +                    app:layout_constraintStart_toStartOf="parent" />
얘도 마진 end 빼고 좌 우 정렬을 초대코드 복사하기 텍스트에 맞추는 게 좋겠네용

2024-02-25 06:27 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        ).show(supportFragmentManager, CHANGE_MODAL)
기존 모달 사용하면 마진이 다르지 않나용? 확인 하셨을까욤??

2024-02-25 06:30 UTC, jihyunniiii commented
좀 전에 단 코리 https://github.com/TeamPINGLE/PINGLE-ANDROID/pull/201/commits/fda97c8963f807e22be58c607f38e671e5fc1bac 이 커밋까지만 보고 단겁니다 ㅠ..ㅠ

2024-02-26 10:19 UTC, DoReMinWoo reviewed
고생하셨어용~~!!!!!!!!

2024-02-26 10:19 UTC, DoReMinWoo commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            }
코드가 한줄인경우 대괄호를 빼는게 예쁜거같아요!
```suggestion
            if (viewModel.getMyGroupIsOwner()) ivMyGroupNowOwner.visibility = View.VISIBLE
            else ivMyGroupNowOwner.visibility = View.INVISIBLE
```

2024-02-26 10:19 UTC, Doreminwoo commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        clipboard.setPrimaryClip(clip)
복사하기랑 공유하기 Util로 빼주시면 제가 재사용하겠습니다~

2024-02-26 10:19 UTC, Doreminwoo commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupViewModel.kt
> +    }
로그는 피알 올릴 때 삭제해주거나 팀버로 바꿔주는게 좋을 것 같아요!

2024-02-26 16:24 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +        <import type="android.view.View" />
아 이거 원래 BindingAdapter에 만들어둔 visibility 이용해서 데바로 바로 View.VISIBLE 이런 식으로 처리해주려고 임포트했었어요ㅜ 근데 안돼서 바꿨는데 까먹고 안 지웠네요 허엉

2024-02-26 16:25 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +            type="org.sopt.pingle.data.datasource.local.PingleLocalDataSource" />
여기도 마찬가지로 .. 바로 접근하려다 안돼서 수정했는데 지우질 않았어여....

2024-02-26 16:27 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        ).show(supportFragmentManager, CHANGE_MODAL)
넹 위에 댓글에서도 말씀드렸능데!! 일단 빌드가 안되는 이유는 모달 이미 만들어져 있는 거에 detail이 null이어야 작동해서 그렇게 수정해두고 커밋은 안 했거든요
띄우는거 테스트해보려고 그랬었구 모달은 새로 만들 겁니당!!

2024-02-26 16:28 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        ).show(supportFragmentManager, CHANGE_MODAL)
넹 확인했서요 AllModalFragment 같은 칭구를 하나 더 만들어서 띄우려구요! 테스트용으로 썼습니둥

2024-02-26 16:29 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            }
이게ㅜㅜ 저도 그렇게 쓰고싶은데 컨트롤 엘이었나 린트였나 돌리면 일케 바뀌더라구요.. if~else문에 braces 없으면 안 좋다 어쩌구 하면서•• 참나!!

2024-02-26 16:29 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupViewModel.kt
> +    }
헉스 ㅎㅅㅎ 바로 삭제하게쑴당

2024-02-27 00:16 UTC, Dan2dani commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            }
저는 가독성 때문에 if, else 괄호 치는게 좋음 ㅋㅋ 개취인듯여 ~~

2024-02-29 07:07 UTC, jihyunniiii requested changes
카페 도착해서 마저 달겠습니당

2024-02-29 07:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +                if (selectedMyGroup!!.isOwner) {
!! <- NPE 발생할 수도 있어서 사용하지 않는 게 좋아요

2024-02-29 07:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        binding.lifecycleOwner = this
이거 이미 BindingActivity에 있지 않나요?

2024-02-29 07:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        binding.toolbarMyGroup.text = getString(R.string.my_group_title)
확장함수 사용해주세용

2024-02-29 07:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +    private fun initAdapter() {
우리 어댑터 초기화 하는 건 initLayout 함수에 넣지 않나요?

2024-02-29 07:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            buttonText = getString(R.string.my_group_modal_change),
여기둥요

2024-02-29 07:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            "핑글 앱을 다운받고, ${viewModel.getGroupName()} 사람들을 만나보세요!\n\n$PINGLE_SHARE_CODE ${viewModel.getGroupCode()} \n\n $PINGLE_PLAY_STORE_LINK"
여기는 스트링 추출이 안 되나요?

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            )
정확한 멘트 전달되면 추가하도록 하겠습니당!

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        startActivity(Intent.createChooser(intent, null))
사실 차이를 잘 모르고 그냥 with는 안 써봐서 찾아보구 썼는데요... with apply 차이를 검색해보니 여기에는 apply가 적합하다는 생각이 들었숩니다 apply 사용으로 변경했어욥ㅎ

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +                android:layout_marginStart="45dp"
거기다 주면 마진값이 더 커져서.. 무슨 의미지용?!

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +            android:paddingHorizontal="@dimen/spacing16"
그러면 그쪽은 리사이클러뷰 터치가 안되지 않나용? 터치영역 잡으려고 이렇게 했숩니다

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +            android:background="@color/g_10"
근데 그러면 !!!!! 테두리가 안 보여요ㅜ

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +            android:gravity="center"
엇 마자요 ㅎ 헤헤 지웠어염

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +            android:layout_marginBottom="20dp"
이거 빼면 리사이클러뷰 영역이 밑으로 주욱 늘어나서 얘가 안 보여염!!

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +            android:layout_marginEnd="7dp"
여기 패딩 때문에 겹치는 영역인데 마진을 뭘로 해야 되는걸까여,,?!

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/res/layout/activity_my_group.xml
> +                    app:layout_constraintStart_toStartOf="parent" />
저기 마진end는 의미가 없어서 지웠습니다! 좌우정렬은 어떤 식으로 맞춰야 하나요?? 메뉴가 공유랑 복사 칸 하나씩 묶여있어서요ㅜ

2024-02-29 11:33 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
> +    override var meetingCount: String
api 연동하면서 로직도 수정하겠습니다! localStorage에는 정말 필요한 정보만 집어넣어두는 걸로 할게욥!!

2024-03-01 04:37 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            "핑글 앱을 다운받고, ${viewModel.getGroupName()} 사람들을 만나보세요!\n\n$PINGLE_SHARE_CODE ${viewModel.getGroupCode()} \n\n $PINGLE_PLAY_STORE_LINK"
위에도 남겨놨는데 푸시하면서 댓글이 또 사라졌나본데요..... 콘텐츠 확정되면 넣으려구 했슴당! 그냥 지금 미리 할게욥ㅎ

2024-03-01 04:38 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +            buttonText = getString(R.string.my_group_modal_change),
넴넴이

2024-03-01 04:38 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        binding.toolbarMyGroup.text = getString(R.string.my_group_title)
ㅣ넹

2024-03-01 04:39 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +    private fun initAdapter() {
엇 이게 컨벤션이 있었나요?! 실행되어야 하는 순서에 따라 어떤 건 onCreate에서 호출하고 어떤 건 initLayout 내부에서 호출하는 걸로 했는데 뭐가 맞나용?

2024-03-01 04:39 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +        binding.lifecycleOwner = this
ㅜ마자요 데바가 안 먹어서 이것저것 해봤던 흔적입니둥.. 지울게염

2024-03-01 04:40 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +                if (selectedMyGroup!!.isOwner) {
넵 let이나 ?로 바꿀게여!!

2024-03-01 06:07 UTC, jihyunniiii reviewed
쏘굿도링 얘네만 수정해주세용

2024-03-01 06:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +    private fun initAdapter() {
헉쓰 이거 이 말이 아니라 그냥 함수 따로 만들지 않고 initLayout 함수에 작성하는 거 아니었냐는 말이었는뎅!!

2024-03-01 06:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +                }
```suggestion
                ivMyGroupSelectedOwner.visibility = if (selectedMyGroup?.isOwner == true) View.VISIBLE else View.INVISIBLE
```

이렇게 적을 수도 있답니다

2024-03-01 06:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/util/component/MyGroupModalDialogFragment.kt
마이 그룹에서만 쓰는 거니까 마이 그룹으로 이동 ㄱㄱ 해주세염

2024-03-01 06:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
> +    startActivity(Intent.createChooser(intent, null))
```suggestion
       Intent(Intent.ACTION_SEND_MULTIPLE).apply {
        type = SHARE_TYPE
        putExtra(Intent.EXTRA_TEXT, shareContent)
        startActivity(Intent.createChooser(this, null))
    }
```

요렇게 써도 됩니둥

2024-03-01 06:07 UTC, jihyunniiii commented on app/src/main/res/drawable/ic_my_group_menu_share.xml
뒤에 _20 넣어줘용 안 넣은 것들 다

2024-03-01 06:07 UTC, jihyunniiii commented on app/src/main/res/drawable/shape_border_radius_12_13.xml
이거 뭔가 다 12인데 디자인 측에서 잘못한 것 같기두,,,??? 한 번 여쭤봐영

2024-03-01 06:15 UTC, HAJIEUN02 commented on app/src/main/res/drawable/shape_border_radius_12_13.xml
> 이거 뭔가 다 12인데 디자인 측에서 잘못한 것 같기두,,,??? 한 번 여쭤봐영

이거 의도한 거 맞는 것 같기두 해여 그 왕관 visible했을 때 오른쪽 아래가 12면 아래 테두리가 살짝쿵 보이더라구욤??

2024-03-01 06:17 UTC, jihyunniiii commented on app/src/main/res/drawable/shape_border_radius_12_13.xml
아하 그래도 혹시 모르니 한 번 물어봐주삼요!!!

2024-03-01 06:21 UTC, HAJIEUN02 commented on app/src/main/res/drawable/shape_border_radius_12_13.xml
넹 피그마 코멘트 남겨놔쑴다~!

2024-03-01 06:22 UTC, HAJIEUN02 commented on app/src/main/res/drawable/ic_my_group_menu_share.xml
완~!

2024-03-01 06:23 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
> +    startActivity(Intent.createChooser(intent, null))
수정 완!!

2024-03-01 06:24 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/util/component/MyGroupModalDialogFragment.kt
넴넴이

2024-03-01 06:25 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
> +                }
오마이갓 쏘간단도리

2024-03-01 12:32 UTC, jihyunniiii approved these changes
쏘굿도링

2024-03-01 12:33 UTC, merged